import type { BrewEntry, Language, Palette, ThemeName } from "./types";

export const paperTexture = require("../../assets/images/paper-texture.png");

export const storageKeys = {
  entries: "brewport.entries.v2",
  language: "brewport.language.v2",
  theme: "brewport.theme.v2",
};

export const palettes: Record<ThemeName, Palette> = {
  crema: {
    label: "Crema",
    zhLabel: "奶油咖啡",
    pageTint: "rgba(248, 242, 229, 0.72)",
    surface: "#FFFDF7",
    raised: "#FFFFFF",
    recessed: "#ECE8DF",
    text: "#32211E",
    muted: "#827770",
    quiet: "#B9B1A9",
    accent: "#C98B3D",
    accentDark: "#945D25",
    accentSoft: "#EADBC8",
    stamp: "#A93630",
    hairline: "rgba(78, 58, 47, 0.09)",
    shadow: "rgba(77, 55, 37, 0.16)",
  },
  sage: {
    label: "Sage",
    zhLabel: "鼠尾草",
    pageTint: "rgba(236, 241, 230, 0.76)",
    surface: "#FCFFF8",
    raised: "#FFFFFF",
    recessed: "#E2E9DB",
    text: "#24332B",
    muted: "#6E7A6E",
    quiet: "#AEB9AA",
    accent: "#71925D",
    accentDark: "#4D6E40",
    accentSoft: "#DDE9D3",
    stamp: "#376643",
    hairline: "rgba(39, 57, 42, 0.09)",
    shadow: "rgba(39, 60, 39, 0.14)",
  },
  graphite: {
    label: "Graphite",
    zhLabel: "石墨灰",
    pageTint: "rgba(238, 240, 240, 0.76)",
    surface: "#FBFBF8",
    raised: "#FFFFFF",
    recessed: "#E3E5E5",
    text: "#20282B",
    muted: "#687276",
    quiet: "#A9B0B2",
    accent: "#557084",
    accentDark: "#344E61",
    accentSoft: "#D8E2E8",
    stamp: "#344D5E",
    hairline: "rgba(32, 44, 48, 0.09)",
    shadow: "rgba(31, 45, 50, 0.14)",
  },
  coral: {
    label: "Coral",
    zhLabel: "珊瑚陶",
    pageTint: "rgba(247, 237, 234, 0.76)",
    surface: "#FFFDFB",
    raised: "#FFFFFF",
    recessed: "#ECE1DD",
    text: "#382527",
    muted: "#7C6D6B",
    quiet: "#B8ACA9",
    accent: "#B9746B",
    accentDark: "#8C4F4B",
    accentSoft: "#EBD8D3",
    stamp: "#994E50",
    hairline: "rgba(74, 43, 43, 0.09)",
    shadow: "rgba(84, 50, 47, 0.14)",
  },
};

export const i18n = {
  en: {
    today: "Today",
    passport: "Passport",
    journal: "Journal",
    allStamps: "All Stamps",
    settings: "Settings",
    map: "Map",
    stamps: "stamps",
    shops: "shops",
    cities: "cities",
    recent: "Selected Day",
    todayAction: "Today",
    empty: "A clean square. Add a cup, a shop, or anything worth collecting.",
    takePhoto: "Take Photo",
    gallery: "Upload from Gallery",
    manual: "Manual Entry",
    close: "Close",
    newStamp: "New Stamp",
    save: "Save Stamp",
    shop: "Shop",
    city: "City",
    item: "Drink / Object",
    note: "Notes",
    rating: "Rating",
    useLocation: "Use Current Location",
    locationReady: "Location attached",
    photoReady: "Photo attached",
    preference: "Preference",
    language: "Language",
    theme: "Color Theme",
    english: "English",
    chinese: "简体中文",
    general: "General",
    privacy: "Privacy & Terms",
    feedback: "Feedback",
    version: "Version 1.0.0",
    permission: "Permission needed",
    cameraPermission: "Camera permission is required to take a photo.",
    galleryPermission: "Photo library permission is required to pick an image.",
    locationPermission: "Location permission is required to save a map point.",
    unknownShop: "Untitled Cafe",
    unknownCity: "Unknown City",
    coffee: "Coffee",
  },
  zh: {
    today: "今天",
    passport: "护照",
    journal: "日历",
    allStamps: "全部印章",
    settings: "设置",
    map: "地图",
    stamps: "枚印章",
    shops: "家店",
    cities: "座城市",
    recent: "选中日期",
    todayAction: "今天",
    empty: "今天还是一张干净的格子，记下一杯咖啡、一家店，或者任何值得收藏的东西。",
    takePhoto: "拍照",
    gallery: "从图库上传",
    manual: "手动记录",
    close: "关闭",
    newStamp: "新印章",
    save: "保存印章",
    shop: "店铺",
    city: "城市",
    item: "饮品 / 物品",
    note: "备注",
    rating: "评分",
    useLocation: "使用当前位置",
    locationReady: "已附加位置",
    photoReady: "已附加照片",
    preference: "偏好设置",
    language: "语言",
    theme: "色系",
    english: "English",
    chinese: "简体中文",
    general: "通用",
    privacy: "隐私与条款",
    feedback: "反馈",
    version: "版本 1.0.0",
    permission: "需要权限",
    cameraPermission: "需要相机权限才能拍照记录。",
    galleryPermission: "需要图库权限才能选择照片。",
    locationPermission: "需要定位权限才能保存地图点位。",
    unknownShop: "未命名咖啡店",
    unknownCity: "未知城市",
    coffee: "咖啡",
  },
} satisfies Record<Language, Record<string, string>>;

export const weekdayLabels = {
  en: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  zh: ["日", "一", "二", "三", "四", "五", "六"],
};

export const seedEntries: BrewEntry[] = [
  {
    id: "sample-1",
    dateISO: "2026-04-28",
    shop: "Rui Xing Coffee Qibao",
    city: "Hangzhou",
    item: "Iced Americano",
    note: "Clean finish, train-station speed.",
    rating: 4,
    location: { latitude: 30.2183, longitude: 120.2108 },
  },
  {
    id: "sample-2",
    dateISO: "2026-04-28",
    shop: "Donggu Park Cafe",
    city: "Hangzhou",
    item: "Coconut Latte",
    note: "Soft, sweet, good afternoon cup.",
    rating: 5,
    location: { latitude: 30.2329, longitude: 120.2271 },
  },
  {
    id: "sample-3",
    dateISO: "2026-05-05",
    shop: "Brew Lovers",
    city: "Shanghai",
    item: "Hand Brew",
    note: "Brew lovers for brew lovers.",
    rating: 5,
    location: { latitude: 31.2304, longitude: 121.4737 },
  },
];
